version: "3.5"

services:
    conan-terminal:
        container_name: conan-terminal${CONTAINER_SUFFIX}
        build:
            dockerfile: Dockerfile
            context: ./conan
        env_file:
            - .creds.env
        networks:
            - primary
        volumes:
           - type: bind
             source: ./examples
             target: /home/conan/examples
        command: tail -f /dev/null
    artifactory-ce:
        container_name: artifactory-ce${CONTAINER_SUFFIX}
        build:
            dockerfile: Dockerfile
            context: ./artifactory
        env_file:
            - .creds.env
        networks:
            primary:
                aliases:
                    - artifactory
        ports:
            - 8081:8081
            - 8082:8082
        restart: always

networks:
    primary:
