version: "3.5"

services:
    conan-terminal:
        container_name: conan-terminal${CONTAINER_SUFFIX}
        build:
            dockerfile: Dockerfile
            context: ./conan
        env_file:
            - .creds.env
        networks:
            - primary
        volumes:
           - type: bind
             source: ./examples
             target: /home/conan/examples
        command: tail -f /dev/null

networks:
    primary:
